### ISSUE TITLE
Migrate to PostCSS

### ISSUE THREAD

**Issue by maximkoretskiy** [snphq/generator-sp#49]
Subtasks:
 - update webpack config
 - update app template
 - update view template

Wanted plugins:
- use
- autoprefixer
- assets
- bem(we should set up our specific settings)
- font-magician
- http://cssnext.io/
- stylelint
- svgo
- size
- browser-reporter
- ...

**Comment by kkateivanova** [comment]
postcss-modules
precss

**Comment by maximkoretskiy** [comment]
We can't implement cssmodules now. We should react to use it

**Comment by maximkoretskiy** [comment]
Also, we shouldn`t use precss. All useful features are present cssnext.
